name: Semantic release

on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16.13.1]
    steps:
      - uses: actions/checkout@v2
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
